# Generated by Django 4.2.28 on 2026-09-01 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(unique=True)),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('high_score', 'Highest single score'), ('aggregate', 'Highest total score')], max_length=16)),
                ('score', models.IntegerField(default=0)),
                ('email_snapshot', models.EmailField(blank=True, max_length=254)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_delete_after', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='events.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished'), ('held', 'Held'), ('invalid', 'Invalid')], db_index=True, default='active', max_length=12)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('play_seconds', models.FloatField(default=0)),
                ('is_clear', models.BooleanField(default=False)),
                ('pause_used', models.BooleanField(default=False)),
                ('seed', models.CharField(max_length=64)),
                ('final_state_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'finished_at'],
                'indexes': [models.Index(fields=['event', 'user', 'status'], name='events_even_event_i_17d7a0_idx'), models.Index(fields=['event', 'status', '-score', 'finished_at'], name='events_even_event_i_53a41d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventprize',
            constraint=models.UniqueConstraint(fields=('event', 'category'), name='unique_event_prize_category'),
        ),
    ]
