# Generated by Django 4.2 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PlayLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anonymous_id", models.CharField(db_index=True, max_length=64)),
                ("run_id", models.CharField(db_index=True, max_length=64)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("play_seconds", models.FloatField(default=0)),
                ("contact_hits", models.PositiveIntegerField(default=0)),
                ("projectile_hits", models.PositiveIntegerField(default=0)),
                ("shooter_contact_hits", models.PositiveIntegerField(default=0)),
                ("shooter_projectile_hits", models.PositiveIntegerField(default=0)),
                ("kills_total", models.PositiveIntegerField(default=0)),
                ("final_score", models.IntegerField(default=0)),
                ("is_clear", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddConstraint(
            model_name="playlog",
            constraint=models.UniqueConstraint(
                fields=("anonymous_id", "run_id"),
                name="unique_playlog_anonymous_run",
            ),
        ),
    ]

